# Generated by Django 6.0.3 on 2026-03-21 16:53

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerCase',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('id', models.UUIDField(default=uuid6.uuid8, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('form_factor', models.CharField(choices=[('ATX', 'ATX'), ('Micro-ATX', 'Micro-ATX'), ('Mini-ITX', 'Mini-ITX'), ('E-ATX', 'E-ATX')], max_length=16, verbose_name='Форм-фактор')),
                ('max_gpu_length', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Максимальная длина видеокарты, мм')),
                ('max_cooler_height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Максимальная высота кулера, мм')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='CoolingSystem',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('id', models.UUIDField(default=uuid6.uuid8, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('cooler_type', models.CharField(choices=[('AIR', 'Воздушное'), ('LIQUID', 'Жидкостное')], max_length=16, verbose_name='Тип охлаждения')),
                ('socket_support', models.CharField(max_length=255, verbose_name='Поддерживаемые сокеты')),
                ('fan_size', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Размер вентилятора, мм')),
                ('tdp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рассеиваемая мощность, Вт')),
            ],
            options={
                'verbose_name': 'Система охлаждения',
                'verbose_name_plural': 'Системы охлаждения',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('id', models.UUIDField(default=uuid6.uuid8, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('socket', models.CharField(max_length=32, verbose_name='Сокет')),
                ('chipset', models.CharField(max_length=64, verbose_name='Чипсет')),
                ('form_factor', models.CharField(choices=[('ATX', 'ATX'), ('Micro-ATX', 'Micro-ATX'), ('Mini-ITX', 'Mini-ITX'), ('E-ATX', 'E-ATX')], max_length=16, verbose_name='Форм-фактор')),
                ('memory_type', models.CharField(choices=[('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=8, verbose_name='Тип памяти')),
                ('memory_slots', models.PositiveSmallIntegerField(verbose_name='Слоты памяти')),
                ('max_memory', models.PositiveSmallIntegerField(verbose_name='Максимум памяти, ГБ')),
            ],
            options={
                'verbose_name': 'Материнская плата',
                'verbose_name_plural': 'Материнские платы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('id', models.UUIDField(default=uuid6.uuid8, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('power', models.PositiveSmallIntegerField(verbose_name='Мощность, Вт')),
                ('efficiency', models.CharField(max_length=32, verbose_name='Сертификат эффективности')),
                ('modular', models.BooleanField(default=False, verbose_name='Модульный')),
                ('form_factor', models.CharField(choices=[('ATX', 'ATX'), ('Micro-ATX', 'Micro-ATX'), ('Mini-ITX', 'Mini-ITX'), ('E-ATX', 'E-ATX')], max_length=16, verbose_name='Форм-фактор')),
            ],
            options={
                'verbose_name': 'Блок питания',
                'verbose_name_plural': 'Блоки питания',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('id', models.UUIDField(default=uuid6.uuid8, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('socket', models.CharField(max_length=32, verbose_name='Сокет')),
                ('cores', models.PositiveSmallIntegerField(verbose_name='Количество ядер')),
                ('threads', models.PositiveSmallIntegerField(verbose_name='Количество потоков')),
                ('base_clock', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Базовая частота, ГГц')),
                ('turbo_clock', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Турбо-частота, ГГц')),
                ('tdp', models.PositiveSmallIntegerField(verbose_name='Теплопакет, Вт')),
            ],
            options={
                'verbose_name': 'Процессор',
                'verbose_name_plural': 'Процессоры',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('id', models.UUIDField(default=uuid6.uuid8, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('memory_type', models.CharField(choices=[('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=8, verbose_name='Тип памяти')),
                ('total_capacity', models.PositiveIntegerField(verbose_name='Общий объём, ГБ')),
                ('modules_count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество модулей')),
                ('frequency', models.PositiveIntegerField(verbose_name='Частота, МГц')),
                ('latency_cl', models.PositiveSmallIntegerField(verbose_name='Тайминг CL')),
            ],
            options={
                'verbose_name': 'Оперативная память',
                'verbose_name_plural': 'Оперативная память',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('id', models.UUIDField(default=uuid6.uuid8, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('storage_type', models.CharField(choices=[('HDD', 'HDD'), ('SSD_SATA', 'SSD SATA'), ('SSD_NVME', 'SSD NVMe')], max_length=16, verbose_name='Тип накопителя')),
                ('capacity', models.PositiveIntegerField(verbose_name='Объём, ГБ')),
                ('interface', models.CharField(max_length=32, verbose_name='Интерфейс')),
                ('read_speed', models.PositiveIntegerField(blank=True, null=True, verbose_name='Скорость чтения, МБ/с')),
                ('write_speed', models.PositiveIntegerField(blank=True, null=True, verbose_name='Скорость записи, МБ/с')),
            ],
            options={
                'verbose_name': 'Накопитель',
                'verbose_name_plural': 'Накопители',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('id', models.UUIDField(default=uuid6.uuid8, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Производитель')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('chipset', models.CharField(max_length=128, verbose_name='Графический процессор')),
                ('memory_size', models.PositiveSmallIntegerField(verbose_name='Объём видеопамяти, ГБ')),
                ('memory_type', models.CharField(max_length=32, verbose_name='Тип видеопамяти')),
                ('length_mm', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Длина, мм')),
                ('tdp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Теплопакет, Вт')),
            ],
            options={
                'verbose_name': 'Видеокарта',
                'verbose_name_plural': 'Видеокарты',
                'ordering': ('-created',),
            },
        ),
    ]
